*&---------------------------------------------------------------------*
*& Include ZLOGIN_PROGRAM_TEAM1TOP                           Module Pool      SAPMZLOGIN_PROGRAM_TEAM1
*&
*&---------------------------------------------------------------------*
PROGRAM SAPMZLOGIN_PROGRAM_TEAM1.

TABLES: ZPRINCIPAL_TB,
        ZSTUDENT_TB,
        ZTEACHER_TB,
        ZNOTICE_TB,
        ZTIMETABLE_TB,
        ZRESULT_TB.
